#!/usr/bin/env bash
# deploy/generate-presigned-url.sh
#
# Generates a short-lived presigned S3 PUT URL for the linkage-engine landing
# bucket. Give this URL to an external party (vendor, partner script, etc.) so
# they can upload a single NDJSON file without needing any AWS credentials.
#
# The URL is scoped to:
#   - One specific object key  (landing/<filename>)
#   - s3:PutObject only
#   - TTL: 3600 seconds (1 hour) by default
#
# The URL is generated by assuming the linkage-engine-uploader-role, which has
# only s3:PutObject on the landing prefix — nothing else.
#
# Usage:
#   ./deploy/generate-presigned-url.sh <filename.ndjson>
#   ./deploy/generate-presigned-url.sh <filename.ndjson> --ttl 7200
#
# Output:
#   Prints the presigned URL to stdout (one line).
#   The external party uploads with:
#     curl -X PUT --upload-file <filename.ndjson> "<presigned-url>"
#
# Requirements:
#   - AWS CLI v2
#   - Python 3 with boto3  (pip3 install boto3)
#   - Caller must have sts:AssumeRole on linkage-engine-uploader-role

set -euo pipefail

REGION="${AWS_REGION:-us-west-1}"
APP="linkage-engine"
BUCKET="${LINKAGE_S3_BUCKET:-${APP}-landing-$(aws sts get-caller-identity --query Account --output text)}"
PREFIX="${LINKAGE_S3_PREFIX:-landing}"
UPLOADER_ROLE_NAME="${APP}-uploader-role"
DEFAULT_TTL=3600

# ── Parse args ────────────────────────────────────────────────────────────────
if [ $# -lt 1 ]; then
  echo "Usage: $0 <filename.ndjson> [--ttl <seconds>]" >&2
  exit 1
fi

FILENAME="$1"
TTL="$DEFAULT_TTL"

shift
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ttl) TTL="$2"; shift 2 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

OBJECT_KEY="${PREFIX}/$(basename "$FILENAME")"

# ── Assume the uploader role ──────────────────────────────────────────────────
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
UPLOADER_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${UPLOADER_ROLE_NAME}"

echo "  Assuming role: ${UPLOADER_ROLE_ARN}" >&2

CREDS=$(aws sts assume-role \
  --role-arn "$UPLOADER_ROLE_ARN" \
  --role-session-name "presign-$(date +%s)" \
  --duration-seconds "$TTL" \
  --query 'Credentials' \
  --output json)

export AWS_ACCESS_KEY_ID=$(echo "$CREDS"     | python3 -c "import sys,json; print(json.load(sys.stdin)['AccessKeyId'])")
export AWS_SECRET_ACCESS_KEY=$(echo "$CREDS" | python3 -c "import sys,json; print(json.load(sys.stdin)['SecretAccessKey'])")
export AWS_SESSION_TOKEN=$(echo "$CREDS"     | python3 -c "import sys,json; print(json.load(sys.stdin)['SessionToken'])")

# ── Generate the presigned URL ────────────────────────────────────────────────
PRESIGNED_URL=$(python3 - <<PYEOF
import boto3, os

s3 = boto3.client(
    "s3",
    region_name="${REGION}",
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"],
    aws_session_token=os.environ["AWS_SESSION_TOKEN"],
)

url = s3.generate_presigned_url(
    "put_object",
    Params={
        "Bucket": "${BUCKET}",
        "Key":    "${OBJECT_KEY}",
        "ContentType": "application/x-ndjson",
    },
    ExpiresIn=${TTL},
)
print(url)
PYEOF
)

# ── Unset temporary credentials ───────────────────────────────────────────────
unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN

# ── Print instructions ────────────────────────────────────────────────────────
echo "" >&2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2
echo "  ✅  Presigned PUT URL generated" >&2
echo "" >&2
echo "  Bucket:  s3://${BUCKET}/${OBJECT_KEY}" >&2
echo "  TTL:     ${TTL}s  (expires $(python3 -c "import datetime; print((datetime.datetime.utcnow()+datetime.timedelta(seconds=${TTL})).strftime('%Y-%m-%dT%H:%M:%SZ'))"))" >&2
echo "" >&2
echo "  Send this URL to the external party." >&2
echo "  They upload with:" >&2
echo "" >&2
echo "    curl -X PUT \\" >&2
echo "      -H 'Content-Type: application/x-ndjson' \\" >&2
echo "      --upload-file ${FILENAME} \\" >&2
echo "      '<URL below>'" >&2
echo "" >&2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >&2

# URL goes to stdout so callers can capture it:  URL=$(./generate-presigned-url.sh file.ndjson)
echo "$PRESIGNED_URL"
